# Generated by Django 3.1 on 2020-08-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='data_call',
            field=models.DateField(default='', verbose_name='Date'),
        ),
    ]
